In [32]:
import os 
import boto3

def download_a_dir_from_s3(bucket_name, bucket_prefix, local_path):
    """
    download the folder from S3 
    
    local: /src/tmp/model_data/
    """
    print "* Helper: Loading Images from S3 {} {}".format(bucket_name,bucket_prefix)
    s3 = boto3.resource('s3')
    mybucket = s3.Bucket(bucket_name)
    # if blank prefix is given, return everything)
    objs = mybucket.objects.filter(
        Prefix = bucket_prefix)
    
    for obj in objs:
        path, filename = os.path.split(obj.key)
        save_path = os.path.join(local_path, path)
        # boto3 s3 download_file will throw exception if folder not exists
        try:
            os.makedirs(save_path)
        except OSError:
            pass
        mybucket.download_file(obj.key, os.path.join(save_path, filename))
        
    # move the folder to target place
    output_path = os.path.join(local_path, bucket_prefix)
    print "* Helper: Images Loaded at: {}".format(output_path)
    return output_path

In [33]:
download_a_dir_from_s3('michaniki', 'models/catVdog_less', '../tmp')

* Helper: Loading Images from S3 michaniki models/catVdog_less
* Helper: Images Loaded at: ../tmp/models/catVdog_less


'../tmp/models/catVdog_less'

In [36]:
'models/path'.split('/')[-1]

'path'

In [38]:
print type(label)

<type 'dict'>


In [43]:
from collections import OrderedDict
new_label = OrderedDict()
for k, v in label.iteritems():
    new_label[v] = k

In [102]:
import json
def save_classes_label_dict(label_dict, file_path_name):
    """
    save the class label dictionary to json
    """
    with open(file_path_name, 'w') as fp:
        json.dump(label_dict, fp)
    
    print "* Helper: Classes Label Json Saved"

save_classes_label_dict(label, "./base.json")

* Helper: Classes Label Json Saved


In [82]:
import numpy as np

d = np.array([[1.000000e+00, 7.484966e-17,3,4,5,6], [3,2,10,1,0,2], [0,1,8,9,1,10]])

In [85]:
for each_list in d:
    i = np.argsort(each_list)[::-1]
    v = np.sort(each_list)[::-1]
    print i,v

[5 4 3 2 0 1] [6.000000e+00 5.000000e+00 4.000000e+00 3.000000e+00 1.000000e+00
 7.484966e-17]
[2 0 5 1 3 4] [10.  3.  2.  2.  1.  0.]
[5 3 2 4 1 0] [10.  9.  8.  1.  1.  0.]


In [90]:
res = map(label.get, i)

In [91]:
res

['electric ray, crampfish, numbfish, torpedo',
 'tiger shark, Galeocerdo cuvieri',
 'great white shark, white shark, man-eater, man-eating shark, Carcharodon carcharias',
 'hammerhead, hammerhead shark',
 'goldfish, Carassius auratus',
 'tench, Tinca tinca']

/d/g.json
